-- EventoSonic: base de datos, autenticación y almacenamiento en Supabase.
-- Ejecutar una sola vez desde Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'equipo',
  created_at timestamptz not null default now()
);

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.app_admins where user_id = (select auth.uid())
  );
$$;

grant execute on function public.is_app_admin() to anon, authenticated;

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  plan_name text not null,
  client_name text not null,
  client_email text not null,
  client_phone text not null,
  event_type text not null,
  event_date date not null,
  guests integer not null check (guests between 1 and 10000),
  extras_text text not null default '',
  special_request text not null default '',
  dietary_text text not null default '',
  base_price integer not null check (base_price >= 0),
  extras_price integer not null check (extras_price >= 0),
  total_price integer not null check (total_price >= 0 and total_price = base_price + extras_price),
  status text not null default 'pendiente' check (status in ('pendiente', 'aceptada', 'rechazada', 'contactada')),
  worker_notes text not null default '',
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 160),
  cover_path text not null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_images (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  storage_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (event_id, storage_path)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists requests_set_updated_at on public.requests;
create trigger requests_set_updated_at before update on public.requests
for each row execute function public.set_updated_at();

drop trigger if exists events_set_updated_at on public.events;
create trigger events_set_updated_at before update on public.events
for each row execute function public.set_updated_at();

alter table public.app_admins enable row level security;
alter table public.requests enable row level security;
alter table public.events enable row level security;
alter table public.event_images enable row level security;

drop policy if exists "admins read own profile" on public.app_admins;
create policy "admins read own profile" on public.app_admins
for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists "admins read requests" on public.requests;
create policy "admins read requests" on public.requests
for select to authenticated using ((select public.is_app_admin()));
drop policy if exists "admins update requests" on public.requests;
create policy "admins update requests" on public.requests
for update to authenticated using ((select public.is_app_admin())) with check ((select public.is_app_admin()));
drop policy if exists "admins delete requests" on public.requests;
create policy "admins delete requests" on public.requests
for delete to authenticated using ((select public.is_app_admin()));

drop policy if exists "events are public" on public.events;
create policy "events are public" on public.events
for select to anon, authenticated using (true);
drop policy if exists "admins create events" on public.events;
create policy "admins create events" on public.events
for insert to authenticated with check ((select public.is_app_admin()) and created_by = (select auth.uid()));
drop policy if exists "admins update events" on public.events;
create policy "admins update events" on public.events
for update to authenticated using ((select public.is_app_admin())) with check ((select public.is_app_admin()));
drop policy if exists "admins delete events" on public.events;
create policy "admins delete events" on public.events
for delete to authenticated using ((select public.is_app_admin()));

drop policy if exists "event images are public" on public.event_images;
create policy "event images are public" on public.event_images
for select to anon, authenticated using (true);
drop policy if exists "admins create event images" on public.event_images;
create policy "admins create event images" on public.event_images
for insert to authenticated with check ((select public.is_app_admin()));
drop policy if exists "admins update event images" on public.event_images;
create policy "admins update event images" on public.event_images
for update to authenticated using ((select public.is_app_admin())) with check ((select public.is_app_admin()));
drop policy if exists "admins delete event images" on public.event_images;
create policy "admins delete event images" on public.event_images
for delete to authenticated using ((select public.is_app_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'event-images',
  'event-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "admins upload event images" on storage.objects;
create policy "admins upload event images" on storage.objects
for insert to authenticated with check (
  bucket_id = 'event-images' and (select public.is_app_admin())
);
drop policy if exists "admins update stored event images" on storage.objects;
create policy "admins update stored event images" on storage.objects
for update to authenticated using (
  bucket_id = 'event-images' and (select public.is_app_admin())
) with check (
  bucket_id = 'event-images' and (select public.is_app_admin())
);
drop policy if exists "admins delete stored event images" on storage.objects;
create policy "admins delete stored event images" on storage.objects
for delete to authenticated using (
  bucket_id = 'event-images' and (select public.is_app_admin())
);

-- Después de crear el usuario de gestión en Authentication > Users, autorízalo con:
-- insert into public.app_admins (user_id, display_name)
-- select id, 'EventoSonic' from auth.users where email = 'TU_EMAIL';
